services:
  - type: web
    name: babu-brgybuddy
    plan: starter
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
