"""alter chat history table, add title

Revision ID: 2138d9f09c35
Revises: 295c5754a239
Create Date: 2024-06-19 15:04:19.649274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2138d9f09c35'
down_revision = '295c5754a239'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('title')
    # ### end Alembic commands ###
