"""add remember me column for token

Revision ID: 48ebae82d2f8
Revises: 9434b63a72c6
Create Date: 2024-06-24 01:20:52.421113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48ebae82d2f8'
down_revision = '9434b63a72c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remember_token', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_users_remember_token', 'users', ['remember_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_remember_token', 'users', type_='unique')
    op.drop_column('users', 'remember_token')
    # ### end Alembic commands ###
