"""empty message

Revision ID: 673190405409
Revises: a36e9d2a5d65
Create Date: 2024-07-07 09:24:34.315512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '673190405409'
down_revision = 'a36e9d2a5d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('birthplace', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    # ### end Alembic commands ###
