"""empty message

Revision ID: 818a766e7aa8
Revises: 5390b5aae0cc
Create Date: 2024-07-17 20:02:16.952240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '818a766e7aa8'
down_revision = '5390b5aae0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new column
    op.add_column('appointment', sa.Column('appointment_id', sa.String(8), nullable=True))
    
    # Generate unique appointment_id for existing rows
    op.execute("""
        UPDATE appointment
        SET appointment_id = SUBSTRING(UUID(), 1, 8)
        WHERE appointment_id IS NULL
    """)
    
    # Make the column non-nullable
    op.alter_column('appointment', 'appointment_id',
               existing_type=sa.String(length=8),
               nullable=False)
    
    # Add unique constraint
    op.create_unique_constraint('uq_appointment_id', 'appointment', ['appointment_id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     # Remove unique constraint
    op.drop_constraint('uq_appointment_id', 'appointment', type_='unique')
    
    # Drop the column
    op.drop_column('appointment', 'appointment_id')
    # ### end Alembic commands ###
