"""alter message table

Revision ID: 9434b63a72c6
Revises: 5c1f89c100b8
Create Date: 2024-06-22 15:32:01.799608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9434b63a72c6'
down_revision = '5c1f89c100b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No database changes required
    op.execute("-- Added cascade='all, delete-orphan' to messages relationship in ChatHistory model")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No database changes required
    op.execute("-- Removed cascade='all, delete-orphan' from messages relationship in ChatHistory model")
    # ### end Alembic commands ###
