"""add lang pref in users

Revision ID: a36e9d2a5d65
Revises: bb96f720b533
Create Date: 2024-06-27 08:32:43.668170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a36e9d2a5d65'
down_revision = 'bb96f720b533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_preference', sa.String(length=10), nullable=False, default="english"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users', 'language_preference')
    # ### end Alembic commands ###
