"""Add ChatHistory

Revision ID: a6e3dd56704d
Revises: 4d88a35a6801
Create Date: 2024-06-15 15:41:47.123226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6e3dd56704d'
down_revision = '4d88a35a6801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('messages', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history')
    # ### end Alembic commands ###
