"""add last_login, total_sessions, total_session_duration columnms in users table

Revision ID: bb96f720b533
Revises: 007849b6e62f
Create Date: 2024-06-24 12:39:23.287117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb96f720b533'
down_revision = '007849b6e62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('total_sessions', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('total_session_duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'total_sessions')
    op.drop_column('users', 'total_session_duration')
    # ### end Alembic commands ###
